# docker-compose run --rm dev-shell
version: "3"
services:
  dev-shell:
    image: "librecorder"
    working_dir: /work
    volumes:
      - $PWD:/work/librecorder
    stdin_open: true
    tty: true
    entrypoint: /bin/bash
